models:
  default: "gpt-4.1-nano"  # Always use gpt-4.1-nano, NOT gpt-4o-mini
  
  filters:
    content_moderation: "gpt-4.1-nano"
    prompt_injection: "gpt-4.1-nano"
    pii_detection: "gpt-4.1-nano"
    toxicity_detection: "gpt-4.1-nano"
    code_generation: "gpt-4.1-nano"
  
  settings:
    temperature: 0.1
    max_tokens: 500
    timeout: 30 