version: "1.0"
pipeline:
  input:
    - name: "length_check"
      type: "length_filter"
      enabled: true
      min_length: 0
      max_length: 10000
      on_error: "block"

    - name: "pii_keywords"
      type: "keyword_list"
      enabled: true
      keywords_file: "src/data/keyword_lists/pii.txt"
      case_sensitive: false
      on_error: "warn"

    - name: "medical_terms"
      type: "keyword_list"
      enabled: true
      keywords_file: "src/data/keyword_lists/medical_terms.txt"
      case_sensitive: false
      on_error: "warn"

 