version: "1.0"
pipeline:
  input:
    - name: "length_check"
      type: "length_filter"
      enabled: true
      min_length: 0
      max_length: 1000
      on_error: "allow"
    
    - name: "openai_content_moderation"
      type: "content_moderation"
      enabled: true
      confidence_threshold: 0.7
      block_categories:
        - "hate"
        - "harassment"
        - "self_harm"
        - "sexual"
        - "violence"
      warn_categories:
        - "sexual_minors"
      on_error: "allow"
    
    - name: "openai_prompt_injection"
      type: "prompt_injection"
      enabled: true
      risk_threshold: 70
      block_levels:
        - "high"
        - "critical"
      warn_levels:
        - "medium"
      on_error: "allow"
    
    - name: "keyword_block"
      type: "keyword_block"
      enabled: true
      keywords: ["idiot", "stupid", "useless", "garbage", "worst", "hate"]
      on_error: "block"
    
    - name: "profanity"
      type: "regex_filter"
      enabled: true
      patterns: ["\\b(shit|hell|damn|fuck|bitch|ass)\\b"]
      action: "block"
      on_error: "block"
  
  output:
    - name: "output_length_check"
      type: "length_filter"
      enabled: true
      min_length: 0
      max_length: 2000
      on_error: "allow"
    
    - name: "output_content_moderation"
      type: "content_moderation"
      enabled: true
      confidence_threshold: 0.8
      block_categories:
        - "hate"
        - "harassment"
        - "self_harm"
        - "sexual"
        - "violence"
      on_error: "warn" 